[providers]
providers = ["node"]

[variables]
PUPPETEER_SKIP_DOWNLOAD = "true"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"

[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
