import { execFile } from 'child_process';
import path from 'path';
import fs from 'fs';
import { getAutoYouTubeTokens } from '@/utils/yt-potoken';
import { getActiveCookieText, markSessionFailed } from '@/utils/db-cookies';

export interface YtDlpFormat {
  format_id: string;
  url: string;
  ext: string;
  vcodec: string;
  acodec: string;
  format_note?: string;
  fps?: number;
  filesize?: number;
  filesize_approx?: number;
  abr?: number;
  tbr?: number;
}

export interface YtDlpInfo {
  title: string;
  description: string;
  duration: number;
  uploader: string;
  uploader_url?: string;
  channel_url?: string;
  thumbnail: string;
  formats: YtDlpFormat[];
  is_restricted?: boolean;
}

/**
 * Convert a semicolon-separated cookie string (e.g. from env / DB) into a
 * Netscape cookie file format that yt-dlp understands, then write it to a
 * temp path and return that path.
 */
function cookieStringToTempFile(cookieString: string): string | null {
  const tmpPath = process.platform !== 'win32'
    ? '/tmp/yt_db_cookies.txt'
    : path.join(process.cwd(), 'env_yt_cookies.txt');

  try {
    let netscape = '# Netscape HTTP Cookie File\n# Generated by ApexDownloader\n\n';
    for (const pair of cookieString.split(';')) {
      const idx = pair.indexOf('=');
      if (idx > 0) {
        const key = pair.substring(0, idx).trim();
        const val = pair.substring(idx + 1).trim();
        netscape += `.youtube.com\tTRUE\t/\tTRUE\t0\t${key}\t${val}\n`;
      }
    }
    fs.writeFileSync(tmpPath, netscape, 'utf8');
    return tmpPath;
  } catch (e) {
    console.error('Failed to write cookie temp file:', e);
    return null;
  }
}

/**
 * Resolve the yt-dlp cookies file path.
 * Priority: DB cookie → env YOUTUBE_COOKIES → local cookies.txt file.
 */
export async function getCookiesFilePath(): Promise<string | null> {
  // 1. Try Neon DB (with env fallback inside getActiveCookieText)
  const dbCookies = await getActiveCookieText('youtube');
  if (dbCookies) {
    return cookieStringToTempFile(dbCookies);
  }

  // 2. Try local cookie files (dev convenience)
  const possiblePaths = [
    path.join(process.cwd(), 'youtube-cookies.txt'),
    path.join(process.cwd(), 'cookies.txt'),
  ];
  for (const p of possiblePaths) {
    if (fs.existsSync(p)) {
      if (process.platform !== 'win32') {
        const tmpCookies = '/tmp/cookies.txt';
        try {
          fs.copyFileSync(p, tmpCookies);
          return tmpCookies;
        } catch (e) {
          console.error('Failed to copy cookies to /tmp:', e);
        }
      }
      return p;
    }
  }

  return null;
}

function getExecutable(): string {
  if (process.platform === 'win32') {
    return 'yt-dlp';
  }
  
  const localPath = path.join(process.cwd(), 'bin', 'yt-dlp');
  if (fs.existsSync(localPath)) {
    const tempPath = '/tmp/yt-dlp';
    try {
      if (!fs.existsSync(tempPath)) {
        fs.copyFileSync(localPath, tempPath);
      }
      fs.chmodSync(tempPath, '755');
      return tempPath;
    } catch (e) {
      console.error('Failed to prepare yt-dlp binary in /tmp:', e);
      return localPath;
    }
  }
  
  return 'yt-dlp'; // Fallback to global
}

function runYtDlp(args: string[]): Promise<YtDlpInfo> {
  return new Promise((resolve, reject) => {
    const exe = getExecutable();
    execFile(exe, ['--dump-json', '--no-warnings', '--no-playlist', ...args], { maxBuffer: 10 * 1024 * 1024 }, (error, stdout, stderr) => {
      if (error) {
        return reject(new Error(stderr.trim() || error.message));
      }
      try {
        resolve(JSON.parse(stdout) as YtDlpInfo);
      } catch (error: unknown) {
        const message = error instanceof Error ? error.message : 'Unknown JSON parsing error';
        reject(new Error(`Failed to parse JSON: ${message}`));
      }
    });
  });
}

export async function getInfo(url: string): Promise<YtDlpInfo> {
  const cookiesPath = await getCookiesFilePath();
  const cookieArgs = cookiesPath ? ['--cookies', cookiesPath] : [];

  // Automatically fetch / load fresh Visitor Data & PO Tokens for 100% automated extraction
  const autoTokens = await getAutoYouTubeTokens();
  const tokenExtractorArgs = autoTokens.visitorData
    ? ['--extractor-args', `youtube:visitor_data=${autoTokens.visitorData}`]
    : [];

  try {
    // Attempt 1: Standard client + cookies + auto Visitor Tokens + Node JS runtime
    const data = await runYtDlp([...cookieArgs, ...tokenExtractorArgs, '--js-runtimes', 'node', url]);
    return { ...data, is_restricted: false };
  } catch (error: unknown) {
    const errMsg = error instanceof Error ? error.message : '';
    console.warn('⚠️ Standard yt-dlp check failed:', errMsg);

    // Detect bot-block and mark DB session as failed so it rotates
    const isBotBlock = errMsg.includes('Sign in to confirm') || errMsg.includes('bot') || errMsg.includes('confirm you');
    if (isBotBlock) {
      console.warn('🔴 Bot block detected — marking current YouTube session as failed.');
      await markSessionFailed('youtube');
      // Fire-and-forget trigger to Render's cookie refresher (if configured)
      const refresherUrl = process.env.NEXT_PUBLIC_MERGER_URL;
      const refresherSecret = process.env.REFRESHER_SECRET;
      if (refresherUrl && refresherSecret) {
        fetch(`${refresherUrl.replace(/\/$/, '')}/api/refresh-cookies`, {
          method: 'POST',
          headers: { 'x-refresher-secret': refresherSecret },
          // No await — fire and forget; don't slow down the download response
        }).catch(e => console.warn('[ytdlp] Refresher trigger failed:', e.message));
      }
    }

    // Attempt 2: Rotate player clients (ios, android, web) to bypass bot verification
    try {
      console.warn('🔄 Retrying with rotated iOS player client...');
      const data = await runYtDlp([...cookieArgs, ...tokenExtractorArgs, '--extractor-args', 'youtube:player_client=ios,android,web', url]);
      return { ...data, is_restricted: true };
    } catch {
      // Attempt 3: Try TV client
      try {
        console.warn('🔄 Retrying with TV embedded player client...');
        const data = await runYtDlp([...cookieArgs, ...tokenExtractorArgs, '--extractor-args', 'youtube:player_client=tv,mweb', url]);
        return { ...data, is_restricted: true };
      } catch (finalErr: unknown) {
        const message = finalErr instanceof Error ? finalErr.message : 'Unknown extraction error';
        throw new Error(`YouTube extraction failed: ${message}`);
      }
    }
  }
}
