const puppeteer = require('puppeteer');
const { spawn, execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const CHROME_EXE = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
const SESSION_DIR = path.join(process.cwd(), 'youtube_session_data');
const COOKIES_TXT_PATH = path.join(process.cwd(), 'cookies.txt');
const ENV_LOCAL_PATH = path.join(process.cwd(), '.env.local');

// Parse CLI Arguments
const args = process.argv.slice(2);
const runBoth = args.includes('--both') || args.length === 0;
const runYt = args.includes('--youtube') || runBoth;
const runIg = args.includes('--instagram') || runBoth;
const syncOnly = args.includes('--sync-only');

function askQuestion(query) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => rl.question(query, (ans) => { rl.close(); resolve(ans.trim()); }));
}

function formatNetscapeCookies(cookies) {
  let output = '# Netscape HTTP Cookie File\n# Auto-generated by Cookie Scraper\n\n';
  for (const c of cookies) {
    const domain = c.domain;
    const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const cookiePath = c.path || '/';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expiry = c.expires ? Math.round(c.expires) : Math.round(Date.now() / 1000 + 365 * 24 * 60 * 60);
    output += `${domain}\t${includeSubdomains}\t${cookiePath}\t${secure}\t${expiry}\t${c.name}\t${c.value}\n`;
  }
  return output;
}

function readEnvLocal() {
  if (fs.existsSync(ENV_LOCAL_PATH)) {
    return fs.readFileSync(ENV_LOCAL_PATH, 'utf8');
  }
  return '';
}

function getEnvVars() {
  const envContent = readEnvLocal();
  const vars = {};
  const lines = envContent.split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const match = trimmed.match(/^([^=]+)=(.*)$/);
    if (match) {
      const key = match[1].trim();
      let val = match[2].trim();
      if (val.startsWith('"') && val.endsWith('"')) {
        val = val.substring(1, val.length - 1).replace(/\\"/g, '"');
      } else if (val.startsWith("'") && val.endsWith("'")) {
        val = val.substring(1, val.length - 1);
      }
      vars[key] = val;
    }
  }
  return vars;
}

function updateEnvVar(key, value) {
  let content = readEnvLocal();
  const lines = content.split('\n').filter(line => !line.trim().startsWith(`${key}=`));
  lines.push(`${key}="${value.replace(/"/g, '\\"')}"`);
  fs.writeFileSync(ENV_LOCAL_PATH, lines.join('\n').trim() + '\n', 'utf8');
}

// ============================================================
// Platform Cookie Extractors
// ============================================================
async function extractYouTube(browser) {
  console.log('  🔍 Extracting YouTube cookies...');
  try {
    const page = await browser.newPage();
    await page.goto('https://www.youtube.com', { waitUntil: 'networkidle2', timeout: 30000 });

    const cookies = await page.cookies('https://www.youtube.com', 'https://youtube.com', 'https://google.com');
    await page.close();

    const hasSid = cookies.some(c => c.name === 'SID');
    if (!hasSid) {
      console.log('  ⚠️  YouTube: No active session found.');
      return null;
    }

    // Save cookies.txt for local yt-dlp
    fs.writeFileSync(COOKIES_TXT_PATH, formatNetscapeCookies(cookies), 'utf8');
    console.log(`  ✅ YouTube: Saved cookies.txt`);

    const cookieString = cookies.map(c => `${c.name}=${c.value}`).join('; ');
    updateEnvVar('YOUTUBE_COOKIES', cookieString);
    return cookieString;
  } catch (err) {
    console.log(`  ❌ YouTube extraction error: ${err.message}`);
    return null;
  }
}

async function extractInstagram(browser) {
  console.log('  🔍 Extracting Instagram cookies...');
  try {
    const page = await browser.newPage();
    await page.goto('https://www.instagram.com', { waitUntil: 'networkidle2', timeout: 30000 });

    const cookies = await page.cookies('https://www.instagram.com', 'https://instagram.com');
    await page.close();

    const sessionCookie = cookies.find(c => c.name === 'sessionid');
    if (!sessionCookie || !sessionCookie.value) {
      console.log('  ⚠️  Instagram: No active session found.');
      return null;
    }

    // Save the single sessionid for compatibility
    updateEnvVar('INSTAGRAM_SESSION_ID', sessionCookie.value);

    // Save the full cookie string to bypass bot detection
    const cookieString = cookies.map(c => `${c.name}=${c.value}`).join('; ');
    updateEnvVar('INSTAGRAM_COOKIES', cookieString);

    console.log(`  ✅ Instagram: Extracted active cookies`);
    return cookieString;
  } catch (err) {
    console.log(`  ❌ Instagram extraction error: ${err.message}`);
    return null;
  }
}

// ============================================================
// Vercel CLI Integrator
// ============================================================
function syncToVercel(key, value) {
  return new Promise((resolve) => {
    console.log(`☁️  Syncing ${key} to Vercel production...`);
    
    // Remove existing variable if present
    try {
      execSync(`vercel env rm ${key} production --yes`, { stdio: 'ignore', shell: true });
    } catch (e) {
      // Ignored
    }

    // Add new variable using secure stdin piping
    const child = spawn('vercel', ['env', 'add', key, 'production'], { shell: true });
    child.stdin.write(value);
    child.stdin.end();

    child.on('close', (code) => {
      if (code === 0) {
        console.log(`  ✅ Successfully updated ${key} on Vercel!`);
      } else {
        console.log(`  ❌ Failed to update ${key} on Vercel (CLI exit code ${code}).`);
        console.log('     Make sure Vercel CLI is installed (npm i -g vercel) and you are logged in (vercel login).');
      }
      resolve();
    });
  });
}

function deployToVercel() {
  return new Promise((resolve) => {
    console.log('\n🚀 Triggering Vercel production deployment...');
    const child = spawn('vercel', ['--prod', '--yes'], { stdio: 'inherit', shell: true });
    child.on('close', (code) => {
      if (code === 0) {
        console.log('\n🎉 Vercel deployment completed successfully!');
      } else {
        console.log(`\n❌ Vercel deployment failed (exit code ${code}).`);
      }
      resolve();
    });
  });
}

// ============================================================
// Native Chrome Control
// ============================================================
function launchChromeNatively() {
  return new Promise((resolve) => {
    console.log('  🌐 Launching Chrome window (NOT automated)...');
    const child = spawn(CHROME_EXE, [
      `--user-data-dir=${SESSION_DIR}`,
      '--no-first-run',
      '--no-default-browser-check',
      'https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Fwww.youtube.com%2F'
    ], { detached: true, stdio: 'ignore' });
    child.unref();
    setTimeout(() => resolve(child), 2000);
  });
}

async function killSessionChrome() {
  return new Promise((resolve) => {
    const { exec } = require('child_process');
    exec(`wmic process where "commandline like '%youtube_session_data%'" get processid /format:list`, (err, stdout) => {
      if (err || !stdout.trim()) { resolve(); return; }
      const pids = stdout.match(/ProcessId=(\d+)/g)?.map(m => m.split('=')[1]) || [];
      for (const pid of pids) {
        try { process.kill(parseInt(pid), 'SIGTERM'); } catch (e) { /* ignore */ }
      }
      setTimeout(resolve, 2000);
    });
  });
}

// ============================================================
// Main Pipeline Orchestrator
// ============================================================
async function run() {
  console.log('╔══════════════════════════════════════════════════╗');
  console.log('║   Unified Cookie Refresher & Vercel Sync Tool    ║');
  console.log('╚══════════════════════════════════════════════════╝\n');

  if (!fs.existsSync(CHROME_EXE)) {
    console.error('❌ Google Chrome not found. Check CHROME_EXE path in script.');
    return;
  }

  let ytCookies = null;
  let igSession = null;

  if (syncOnly) {
    console.log('☁️  Skipping browser extraction. Reading cookies from .env.local to sync only...');
    const localVars = getEnvVars();
    ytCookies = localVars['YOUTUBE_COOKIES'];
    igSession = localVars['INSTAGRAM_COOKIES'];
  } else {
    const hasCachedSession = fs.existsSync(SESSION_DIR) && fs.readdirSync(SESSION_DIR).length > 0;

    // --- STEP 1: Attempt Headless Extraction first ---
    if (hasCachedSession) {
      console.log('📦 Cached session found. Attempting headless extraction...');
      try {
        const browser = await puppeteer.launch({
          headless: true,
          executablePath: CHROME_EXE,
          userDataDir: SESSION_DIR,
          args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-gpu']
        });

        // Run processes in parallel or separately depending on arguments
        const promises = [];
        if (runYt) promises.push(extractYouTube(browser));
        else promises.push(Promise.resolve(null));

        if (runIg) promises.push(extractInstagram(browser));
        else promises.push(Promise.resolve(null));

        const results = await Promise.all(promises);
        ytCookies = results[0];
        igSession = results[1];

        await browser.close();
      } catch (err) {
        console.log('  ⚠️ Headless extraction failed:', err.message);
      }
    }

    // --- STEP 2: Interactive Sign-in Fallback ---
    if ((runYt && !ytCookies) || (runIg && !igSession)) {
      console.log('\n⚠️ Active login session(s) missing or expired.');
      console.log('╔════════════════════════════════════════════════════════╗');
      console.log('║  A normal Chrome window will open.                     ║');
      console.log('║                                                        ║');
      if (runYt) console.log('║  1. Sign in to your Google/YouTube account             ║');
      if (runIg) console.log('║  2. Open a new tab -> go to instagram.com and sign in  ║');
      console.log('║  3. Once logged in, CLOSE Chrome completely            ║');
      console.log('║  4. Come back here and press ENTER                     ║');
      console.log('╚════════════════════════════════════════════════════════╝\n');

      await launchChromeNatively();
      await askQuestion('Press ENTER after you have logged in and CLOSED Chrome...');
      await killSessionChrome();
      await new Promise(r => setTimeout(r, 1000));

      // Try extraction again headlessly
      console.log('\n📦 Extracting refreshed session cookies...');
      const browser = await puppeteer.launch({
        headless: true,
        executablePath: CHROME_EXE,
        userDataDir: SESSION_DIR,
        args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-gpu']
      });

      const promises = [];
      if (runYt) promises.push(extractYouTube(browser));
      else promises.push(Promise.resolve(null));

      if (runIg) promises.push(extractInstagram(browser));
      else promises.push(Promise.resolve(null));

      const results = await Promise.all(promises);
      ytCookies = results[0];
      igSession = results[1];

      await browser.close();
    }
  }

  // --- STEP 3: Vercel Push ---
  let hasSyncedAny = false;

  if (runYt && ytCookies) {
    await syncToVercel('YOUTUBE_COOKIES', ytCookies);
    hasSyncedAny = true;
  }
  if (runIg && igSession) {
    const sessionIdOnly = igSession.split('; ').find(c => c.startsWith('sessionid='))?.split('=')[1] || '';
    if (sessionIdOnly) {
      await syncToVercel('INSTAGRAM_SESSION_ID', sessionIdOnly);
    }
    await syncToVercel('INSTAGRAM_COOKIES', igSession);
    hasSyncedAny = true;
  }

  // --- STEP 4: Trigger Vercel deploy if anything was synced or syncOnly requested ---
  if (hasSyncedAny || syncOnly) {
    await deployToVercel();
  } else {
    console.log('\n❌ No cookies extracted or synced. Skip deployment.');
  }
}

run().catch(err => console.error('Fatal Error:', err));
